Cargo.toml, README.md, src/bin/carina.rs, src/database.rs, src/ion_series.rs, src/mass.rs, src/spectrum.rs
`spectrum_q_value` is probably cheating and leaking some latent information about target/decoy class (#1).
Instead, we compute other features on the candidate peptide-spectrum level that are agnostic to target/decoy class:
- matched_intensity_pct: percentage of total MS2 signal that the matched peaks account for,
- delta_matched: difference between # of matched peaks of reported PSM, and the average peaks/candidate
- scored_candidates: # of candidates actually scored 
- spectrum_z_score: z-score of candidate hyperscore vs median hyperscore of all candidates
Additional perf enhancements:
- Remove `HashMap` from `Scorer::score` and pre-allocating a score vector based on the theoretical # of candidates that can be scored
- Use `sort_unstable` rather than `sort`
Perf on 4-core i5-4690k, 16 GB …
=> Investigate PSM regression, re-engineer features for SVM, perf enhancements

.github/workflows/build.yml, .github/workflows/upload_artifacts/action.yml
This PR adds a GitHub workflow to build Sage on:
- Linux x86_64 (using Ubuntu 14.04)
- Windows x86_64
- MacOS x86_64
- MacOS aarch64 (for Apple Silicon)
The builds are triggered on new PRs and commits to master, and the executables are uploaded as artifacts automatically for manual inspection, if desired.
New GitHub releases trigger this workflow and additionally the executables will be automatically uploaded as assets to the new release.
=> Add build and release action

.github/workflows/docker.yml, Dockerfile
This PR adds a Github workflow to build an Alpine-based Docker image for Sage.
Docker images are build with each commit to master (should have the `master` tag), and on new releases (should have the release tag). I've configured it to upload the images to the [Github Container Registry](https://github.com/features/packages), but it can be easily configured to upload to Dockerhub, AWS ECR, etc.
The image is multiplatform, covering x86_64 and arm64 architectures on Linux.
=> Add a Sage Docker image

.github/workflows/rust.yml, Cargo.toml, src/bin/sage.rs, src/database.rs, tests/config-cli.json
This PR adds some parameters to the CLI, which overide the configuration provided in the param file. The included parameters are:
- `mzml_paths`
- `database.fasta`
- `output_directory`
This makes it easier to construct a default config file and use it for many analyses. Now you can run:
```sh
sage config.json
sage -f proteins.fasta -o cool_project config.json
sage -f proteins.fasta config.json *.mzML
```
I didn't write tests... mostly because I don't know how to test a Rust CLI yet.
*Please note that I just finished reading the Rust book this weekend, so certainly no offense if there's a lot of changes to make.* 😆
=> Specify some parameters from the CLI

Dockerfile
This PR just adds Bash to the Docker image, which is a prerequisite for NextFlow containers. I think it only adds ~1MB to the image size.
=> Added bash to Docker container

README.md
Hello there!
First off, I am very impressed by the project so I wanted to make a minor contribution to the documentation. I added "installation" instructions for the pre-compiled binaries in the github releases.
In an additional effort to improve documentation:
-  On the "notes" you also mention:
> - The majority of parameters are optional - only "database.fasta", "precursor_tol", and "fragment_tol" are required. Sage will try and use reasonable defaults for any parameters not supplied
I am assuming that means reasonable for data-dependent narrow-window high-resolution ms2 runs, right? Should that be explicit?
- Should a page be added to explain all the features used internally for re-scoring?
https://github.com/lazear/sage/pull/19
Thanks a lot for the great project!
Sebastian
=> Update readme to mention the github releases

.github/workflows/build.yml, .github/workflows/docker.yml
I adapted the CI configuration from ripgrep https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml and kept the structure of the existing configuration.
- binaries are named `sage` (`sage.exe` on Windows) 
- binaries are compressed in `tar.gz` (or `zip` on Windows) archives named like `sage-[version]-[target].tar.gz`  (Fixes #23)
- refactor Linux and Windows job like the MacOS one using matrix for consistency and to allow further extension of the matrices, or merge of the 3 jobs eventually
- `Build Sage Executables` and `Build Docker image` now only run on releases not on every push to master
- whitespace changes due to my format on save make it look like I changed a lot :(
=> update CI to compress binaries in archive at release

CHANGELOG.md, Cargo.lock, README.md, crates/sage-cli/Cargo.toml, crates/sage-cli/src/main.rs, crates/sage-cloudpath/Cargo.toml, crates/sage-cloudpath/src/lib.rs, crates/sage/Cargo.toml, crates/sage/src/database.rs, crates/sage/src/fasta.rs, crates/sage/src/lfq.rs, crates/sage/src/mass.rs, crates/sage/src/mzml.rs, crates/sage/src/peptide.rs, crates/sage/src/scoring.rs, crates/sage/src/spectrum.rs, crates/sage/src/tmt.rs
This is a more correct thing to do - mzML files are not guaranteed to have a "scan=(\d)" part in the spectrum id field
**Breaking changes:**
- Add a `rank` column to output file
- Rename `discriminant_score` to `sage_discriminant_score`
- Use base proforma notation for peptide mods, i.e. "[+304.2071]-PEPTIDEM[+15.9949]AAC[+57.0214]H"
- Replace scannr with nativeID, i.e. "controllerType=0 controllerNumber=1 scan=30069"
=> Keep track of spectrum nativeIDs, rather than scan number

.github/workflows/docker.yml, Dockerfile
I was having trouble with interoperability using a Alpine-based image (mostly trying to use the AWS CLI, even through the host system). I think transitioning to a Debian-based image that uses glibc instead of musl would resolve some headaches 🙃.
=> Change docker image from Alpine to Debian

Dockerfile
Sorry for the PR spam!
I was too quick my last PR and forgot that NextFlow needs the `ps` command for tracing, and the debian slim base images don't have `procps` installed by default. Anyways, this PR installs `procps` so that it should work nicely.
Hopefully this is the last Docker image update for awhile 😅
=> Add procps to Docker image

README.md, crates/sage-cli/src/main.rs, crates/sage/src/enzyme.rs, crates/sage/src/ml/gauss.rs, crates/sage/src/ml/linear_discriminant.rs, crates/sage/src/ml/mod.rs, crates/sage/src/ml/retention_alignment.rs, crates/sage/src/ml/retention_model.rs, crates/sage/src/scoring.rs
This PR introduces improvements to retention time prediction, and increase stability of the linear equations solver
**RT**
Retention times are now globally aligned across files:
- Normalize RTs within a file to unit scale (0.0 - 1.0)
- Align each file following https://pubmed.ncbi.nlm.nih.gov/31260443/
RT prediction is then performed on all files at once (on aligned RTs), rather than one file at a time - previously, there were many instances where some files in a search could not have RTs predicted, decreasing the effectiveness of delta_rt as a feature for LDA.
**Sequence Deduplication**
Peptide sequences within a protein are now deduplicated - previously, repeated peptides would be called multiple times for the same protein (e.g. `num_proteins` > 1 even if the peptide was unique) …
=> Global retention time alignment

CHANGELOG.md, crates/sage-cli/src/input.rs, crates/sage-cli/src/main.rs, crates/sage-cli/src/output.rs, crates/sage-cli/tests/integration.rs, crates/sage/src/database.rs, crates/sage/src/enzyme.rs, crates/sage/src/fasta.rs, crates/sage/src/fdr.rs, crates/sage/src/ion_series.rs, crates/sage/src/lfq.rs, crates/sage/src/lib.rs, crates/sage/src/mass.rs, crates/sage/src/ml/retention_model.rs, crates/sage/src/modification.rs, crates/sage/src/peptide.rs, crates/sage/src/scoring.rs, crates/sage/src/spectrum.rs
This PR adds support for multiple variable modifications, and peptide/protein-terminal modifications that are specific to individual amino acids. This also overhauls both the internal data representation of `Peptide`, and how modifications are applied. This speeds up fragment index creation significantly (and should reduce memory usage), but it is still somewhat slow for large numbers of variable modifications - something to improve in the future!
The new syntax looks like this:
```json
"variable_mods": {
"M": [15.9949],
"^Q": -17.026549,
"^E": -18.010565,
"[": 42.010565
},
```
Either a single floating point number (`-18.0`) or a list of floating point numbers (`[-18.0, -15.2]`) can be supplied as modifications.
- "^X": Modification to be applied to amino acid X if it appears at the …
=> Overhaul modifications: multiple variable mods, modifications of specific AA at termini

CHANGELOG.md, DOCS.md, crates/sage-cli/src/output.rs, crates/sage/src/database.rs, crates/sage/src/enzyme.rs, crates/sage/src/peptide.rs
This update adds a semi-enzymatic function with new notation. "?KR" would produce all non-specific digests between all tryptic peptides. This update can also account for missed cleavages.
Updated the broken code in my previously PR
=> Closes #92 New semi-enzymatic function with new notation.

crates/sage-cli/src/main.rs, crates/sage-cli/src/output.rs, crates/sage-cloudpath/src/mzml.rs, crates/sage-cloudpath/src/tdf.rs, crates/sage/src/ml/linear_discriminant.rs, crates/sage/src/ml/mobility_model.rs, crates/sage/src/ml/mod.rs, crates/sage/src/scoring.rs, crates/sage/src/spectrum.rs
This PR adds two main things.
1. Reading of 1/k0 values from timstof (.d/*.tdf) and .mzml files (when available), as well as reporting them.
2. Modeling of the 1/k0 for rescoring. The model is greatly based on the retention time model already being used, with some "minor" feature engineering.
- Some of the prediction logic has also been changed so the mobility model can fail independently from the rt alignment (failed IMS predictions dont break alignment).
- It is worth noting that this rescoring (at least for tryptic peptides) only increases the number of identified peptides with q<0.01 by ~1% for most of my tryptic peptide data.
Discussed here: https://github.com/lazear/sage/issues/73
LMK what you think!
Best
-Sebastian
=> Feature: ims model

crates/sage-cloudpath/src/mzml.rs
Adds the option to extract ion mobilities from mzML files that encode it in the scan section instead of the selected ion section (which was not something i knew could happen)
https://github.com/lazear/sage/issues/117
=> Fix to #117

Cargo.lock, crates/sage-cloudpath/Cargo.toml, crates/sage-cloudpath/src/tdf.rs
Hi @lazear,
We had some issues matching Sage PSMs to spectra when read directly from TDF files. After conferring with @sander-willems-bruker, we found out there was some confusion in how precursor vs spectrum IDs are handled between different tools. For now, using the spectrum index seems to be the best way forward.
The PR also updates the timsrust version to 0.2.4.
=> TDF: Use spectrum index instead of precursor index

Cargo.lock, crates/sage-cli/src/main.rs, crates/sage-cloudpath/Cargo.toml, crates/sage-cloudpath/src/tdf.rs
PR that uses the latest toimsrust 0.3.0 package. This is major refactoring that 
* improves readability of timsrust code
* more clearly allows parallel spectrum reading
* allows to read diaPASEF windows as if they are spectra, allowing direct reading/processing of `raw_dia.d` data (results are not impressive compared to peptide centric searching though, but the mere capability is very useful for quick investigation of dia files).
=> Timsrust 0.3.0

DOCS.md
First step to: https://github.com/lazear/sage/issues/157
I noticed as well that some of the new additions are not documented ... is that something we would like to get going? (alternative scoring + bruker processing options). I can take care of the bruker options... but I am not sure if they might be a lil too unstable/untested to document.
=> docs: remove mention of deleted parameters

crates/sage-cli/src/input.rs, crates/sage-cli/src/main.rs, crates/sage-cli/src/runner.rs, crates/sage/src/database.rs, crates/sage/src/fasta.rs, crates/sage/src/scoring.rs
With this PR we allow the database to be split. This is especially helpful to control the memory for non-specific searches such as immuno, i.e. when setting `"cleave_at": ""` or many PTMs. The core concept is to iterate over fasta chunks rather than creating a db based on the whole fasta. Based on these chunks, only relevant peptides will be retained. After quickly filtering the database like this, all potential peptide hits are collected to make a final (severely) filtered database that is used for a native Sage search without any code alterations.
The memory seems to be very well controlled with this approach. The (identification) results are almost the same as doing searches without chunking, but for any specific chunk size there are some minor (generally <1%) differences as some …
=> Db splitting

.github/workflows/docker.yml
Well this is mostly to allow forks to run the full CI ... not really a lot otherwise ...
=> CI: Docker user user instead of `lazear` as a container name

Cargo.lock, crates/sage-cli/Cargo.toml, crates/sage-cli/src/input.rs, crates/sage-cli/src/main.rs, crates/sage-cli/src/runner.rs
This PR adds the option to generate an interactive html report that summarizes the results from Sage, and plots some QC plots for inspecting the scoring and correlation of predicted RT/IM. This also addresses #168, although the stats summary table is downloadable within the html report. Should it also be directly written out to a tsv file?
* [`crates/sage-cli/Cargo.toml`](diffhunk://#diff-51bf80e504a91dc8d5cf98184ae8fa6e390efaa4b9f15e1b50800f45458e0253R39-R40): Added `maud` and `report-builder` dependencies to support HTML report generation.
* [`crates/sage-cli/src/input.rs`](diffhunk://#diff-91d03b760c38081ab09a644a9d7cc3aeeed02628b0dff782dac7f37147e628f3R43-R45): Updated the `Search` and `Input` structs to include a new `write_report` field.
* …
=> Feature/html results/QC report

Cargo.lock, crates/sage-cli/src/runner.rs, crates/sage/src/database.rs, crates/sage/src/scoring.rs
This PR reduces allocations in several places:
- Rather than allocating a vector of peptides for each iteration of a tight loop, atomics are used to maintain a set of identified peptides
- Existing peptides are drained from the temporary/chunked databases rather than cloning them
One apparent logic error is also addressed:
- If `prefilter_low_memory` was turned on, all preliminary hits were still retained, rather than only `report_psms`
=> Prefiltering performance optimizations
